_lemon-rule:
  selected-node-name: &selected-node-name 🏳️‍⚧️Target Node

proxy-groups:
  # For default UDP request
  - name: Default-UDP
    type: select
    proxies:
      - *selected-node-name
      - DIRECT
      - REJECT
      - REJECT-DROP
  # For each request that dosn't have a match
  - name: Default
    type: select
    proxies:
      - *selected-node-name
      - DIRECT
rules:
  # Default-UDP
  - NETWORK,udp,Default-UDP
  # Default
  - MATCH,Default
